-- Add pitch_emails column to release_requests
-- Stores the 5 personalized journalist pitch emails generated by /api/ai/generate-pitches
-- Each entry: { journalist, outlet, beat, subject, body }

ALTER TABLE release_requests
  ADD COLUMN IF NOT EXISTS pitch_emails jsonb;

COMMENT ON COLUMN release_requests.pitch_emails IS 'Array of 5 personalized pitch emails: {journalist, outlet, beat, subject, body}';
